class SuraModel {
  final int id;
  final String englishName;
  final String arabicName;
  final String versesCount;

  SuraModel({
    required this.id,
    required this.englishName,
    required this.arabicName,
    required this.versesCount,
  });

  static List<SuraModel> suraList = [
    SuraModel(
      id: 1,
      englishName: "Al-Fatiha",
      arabicName: "الفاتحه",
      versesCount: "7 Verses",
    ),
    SuraModel(
      id: 2,
      englishName: "Al-Baqarah",
      arabicName: "البقرة",
      versesCount: "286 Verses",
    ),
    SuraModel(
      id: 3,
      englishName: "Aal-E-Imran",
      arabicName: "آل عمران",
      versesCount: "200 Verses",
    ),
    SuraModel(
      id: 4,
      englishName: "An-Nisa",
      arabicName: "النساء",
      versesCount: "176 Verses",
    ),
    SuraModel(
      id: 5,
      englishName: "Al-Ma'idah",
      arabicName: "المائدة",
      versesCount: "120 Verses",
    ),
    SuraModel(
      id: 6,
      englishName: "Al-An'am",
      arabicName: "الأنعام",
      versesCount: "165 Verses",
    ),
    SuraModel(
      id: 7,
      englishName: "Al-A'raf",
      arabicName: "الأعراف",
      versesCount: "206 Verses",
    ),
    SuraModel(
      id: 8,
      englishName: "Al-Anfal",
      arabicName: "الأنفال",
      versesCount: "75 Verses",
    ),
    SuraModel(
      id: 9,
      englishName: "At-Tawbah",
      arabicName: "التوبة",
      versesCount: "129 Verses",
    ),
    SuraModel(
      id: 10,
      englishName: "Yunus",
      arabicName: "يونس",
      versesCount: "109 Verses",
    ),
    SuraModel(
      id: 11,
      englishName: "Hud",
      arabicName: "هود",
      versesCount: "123 Verses",
    ),
    SuraModel(
      id: 12,
      englishName: "Yusuf",
      arabicName: "يوسف",
      versesCount: "111 Verses",
    ),
    SuraModel(
      id: 13,
      englishName: "Ar-Ra'd",
      arabicName: "الرعد",
      versesCount: "43 Verses",
    ),
    SuraModel(
      id: 14,
      englishName: "Ibrahim",
      arabicName: "إبراهيم",
      versesCount: "52 Verses",
    ),
    SuraModel(
      id: 15,
      englishName: "Al-Hijr",
      arabicName: "الحجر",
      versesCount: "99 Verses",
    ),
    SuraModel(
      id: 16,
      englishName: "An-Nahl",
      arabicName: "النحل",
      versesCount: "128 Verses",
    ),
    SuraModel(
      id: 17,
      englishName: "Al-Isra",
      arabicName: "الإسراء",
      versesCount: "111 Verses",
    ),
    SuraModel(
      id: 18,
      englishName: "Al-Kahf",
      arabicName: "الكهف",
      versesCount: "110 Verses",
    ),
    SuraModel(
      id: 19,
      englishName: "Maryam",
      arabicName: "مريم",
      versesCount: "98 Verses",
    ),
    SuraModel(
      id: 20,
      englishName: "Ta-Ha",
      arabicName: "طه",
      versesCount: "135 Verses",
    ),
    SuraModel(
      id: 21,
      englishName: "Al-Anbiya",
      arabicName: "الأنبياء",
      versesCount: "112 Verses",
    ),
    SuraModel(
      id: 22,
      englishName: "Al-Hajj",
      arabicName: "الحج",
      versesCount: "78 Verses",
    ),
    SuraModel(
      id: 23,
      englishName: "Al-Mu'minun",
      arabicName: "المؤمنون",
      versesCount: "118 Verses",
    ),
    SuraModel(
      id: 24,
      englishName: "An-Nur",
      arabicName: "النور",
      versesCount: "64 Verses",
    ),
    SuraModel(
      id: 25,
      englishName: "Al-Furqan",
      arabicName: "الفرقان",
      versesCount: "77 Verses",
    ),
    SuraModel(
      id: 26,
      englishName: "Ash-Shu'ara",
      arabicName: "الشعراء",
      versesCount: "227 Verses",
    ),
    SuraModel(
      id: 27,
      englishName: "An-Naml",
      arabicName: "النمل",
      versesCount: "93 Verses",
    ),
    SuraModel(
      id: 28,
      englishName: "Al-Qasas",
      arabicName: "القصص",
      versesCount: "88 Verses",
    ),
    SuraModel(
      id: 29,
      englishName: "Al-Ankabut",
      arabicName: "العنكبوت",
      versesCount: "69 Verses",
    ),
    SuraModel(
      id: 30,
      englishName: "Ar-Rum",
      arabicName: "الروم",
      versesCount: "60 Verses",
    ),
    SuraModel(
      id: 31,
      englishName: "Luqman",
      arabicName: "لقمان",
      versesCount: "34 Verses",
    ),
    SuraModel(
      id: 32,
      englishName: "As-Sajdah",
      arabicName: "السجدة",
      versesCount: "30 Verses",
    ),
    SuraModel(
      id: 33,
      englishName: "Al-Ahzab",
      arabicName: "الأحزاب",
      versesCount: "73 Verses",
    ),
    SuraModel(
      id: 34,
      englishName: "Saba",
      arabicName: "سبأ",
      versesCount: "54 Verses",
    ),
    SuraModel(
      id: 35,
      englishName: "Fatir",
      arabicName: "فاطر",
      versesCount: "45 Verses",
    ),
    SuraModel(
      id: 36,
      englishName: "Ya-Sin",
      arabicName: "يس",
      versesCount: "83 Verses",
    ),
    SuraModel(
      id: 37,
      englishName: "As-Saffat",
      arabicName: "الصافات",
      versesCount: "182 Verses",
    ),
    SuraModel(
      id: 38,
      englishName: "Sad",
      arabicName: "ص",
      versesCount: "88 Verses",
    ),
    SuraModel(
      id: 39,
      englishName: "Az-Zumar",
      arabicName: "الزمر",
      versesCount: "75 Verses",
    ),
    SuraModel(
      id: 40,
      englishName: "Ghafir",
      arabicName: "غافر",
      versesCount: "85 Verses",
    ),
    SuraModel(
      id: 41,
      englishName: "Fussilat",
      arabicName: "فصلت",
      versesCount: "54 Verses",
    ),
    SuraModel(
      id: 42,
      englishName: "Ash-Shura",
      arabicName: "الشورى",
      versesCount: "53 Verses",
    ),
    SuraModel(
      id: 43,
      englishName: "Az-Zukhruf",
      arabicName: "الزخرف",
      versesCount: "89 Verses",
    ),
    SuraModel(
      id: 44,
      englishName: "Ad-Dukhan",
      arabicName: "الدخان",
      versesCount: "59 Verses",
    ),
    SuraModel(
      id: 45,
      englishName: "Al-Jathiyah",
      arabicName: "الجاثية",
      versesCount: "37 Verses",
    ),
    SuraModel(
      id: 46,
      englishName: "Al-Ahqaf",
      arabicName: "الأحقاف",
      versesCount: "35 Verses",
    ),
    SuraModel(
      id: 47,
      englishName: "Muhammad",
      arabicName: "محمد",
      versesCount: "38 Verses",
    ),
    SuraModel(
      id: 48,
      englishName: "Al-Fath",
      arabicName: "الفتح",
      versesCount: "29 Verses",
    ),
    SuraModel(
      id: 49,
      englishName: "Al-Hujurat",
      arabicName: "الحجرات",
      versesCount: "18 Verses",
    ),
    SuraModel(
      id: 50,
      englishName: "Qaf",
      arabicName: "ق",
      versesCount: "45 Verses",
    ),
    SuraModel(
      id: 51,
      englishName: "Adh-Dhariyat",
      arabicName: "الذاريات",
      versesCount: "60 Verses",
    ),
    SuraModel(
      id: 52,
      englishName: "At-Tur",
      arabicName: "الطور",
      versesCount: "49 Verses",
    ),
    SuraModel(
      id: 53,
      englishName: "An-Najm",
      arabicName: "النجم",
      versesCount: "62 Verses",
    ),
    SuraModel(
      id: 54,
      englishName: "Al-Qamar",
      arabicName: "القمر",
      versesCount: "55 Verses",
    ),
    SuraModel(
      id: 55,
      englishName: "Ar-Rahman",
      arabicName: "الرحمن",
      versesCount: "78 Verses",
    ),
    SuraModel(
      id: 56,
      englishName: "Al-Waqi'ah",
      arabicName: "الواقعة",
      versesCount: "96 Verses",
    ),
    SuraModel(
      id: 57,
      englishName: "Al-Hadid",
      arabicName: "الحديد",
      versesCount: "29 Verses",
    ),
    SuraModel(
      id: 58,
      englishName: "Al-Mujadila",
      arabicName: "المجادلة",
      versesCount: "22 Verses",
    ),
    SuraModel(
      id: 59,
      englishName: "Al-Hashr",
      arabicName: "الحشر",
      versesCount: "24 Verses",
    ),
    SuraModel(
      id: 60,
      englishName: "Al-Mumtahanah",
      arabicName: "الممتحنة",
      versesCount: "13 Verses",
    ),
    SuraModel(
      id: 61,
      englishName: "As-Saff",
      arabicName: "الصف",
      versesCount: "14 Verses",
    ),
    SuraModel(
      id: 62,
      englishName: "Al-Jumu'ah",
      arabicName: "الجمعة",
      versesCount: "11 Verses",
    ),
    SuraModel(
      id: 63,
      englishName: "Al-Munafiqun",
      arabicName: "المنافقون",
      versesCount: "11 Verses",
    ),
    SuraModel(
      id: 64,
      englishName: "At-Taghabun",
      arabicName: "التغابن",
      versesCount: "18 Verses",
    ),
    SuraModel(
      id: 65,
      englishName: "At-Talaq",
      arabicName: "الطلاق",
      versesCount: "12 Verses",
    ),
    SuraModel(
      id: 66,
      englishName: "At-Tahrim",
      arabicName: "التحريم",
      versesCount: "12 Verses",
    ),
    SuraModel(
      id: 67,
      englishName: "Al-Mulk",
      arabicName: "الملك",
      versesCount: "30 Verses",
    ),
    SuraModel(
      id: 68,
      englishName: "Al-Qalam",
      arabicName: "القلم",
      versesCount: "52 Verses",
    ),
    SuraModel(
      id: 69,
      englishName: "Al-Haqqah",
      arabicName: "الحاقة",
      versesCount: "52 Verses",
    ),
    SuraModel(
      id: 70,
      englishName: "Al-Ma'arij",
      arabicName: "المعارج",
      versesCount: "44 Verses",
    ),
    SuraModel(
      id: 71,
      englishName: "Nuh",
      arabicName: "نوح",
      versesCount: "28 Verses",
    ),
    SuraModel(
      id: 72,
      englishName: "Al-Jinn",
      arabicName: "الجن",
      versesCount: "28 Verses",
    ),
    SuraModel(
      id: 73,
      englishName: "Al-Muzzammil",
      arabicName: "المزمل",
      versesCount: "20 Verses",
    ),
    SuraModel(
      id: 74,
      englishName: "Al-Muddaththir",
      arabicName: "المدثر",
      versesCount: "56 Verses",
    ),
    SuraModel(
      id: 75,
      englishName: "Al-Qiyamah",
      arabicName: "القيامة",
      versesCount: "40 Verses",
    ),
    SuraModel(
      id: 76,
      englishName: "Al-Insan",
      arabicName: "الإنسان",
      versesCount: "31 Verses",
    ),
    SuraModel(
      id: 77,
      englishName: "Al-Mursalat",
      arabicName: "المرسلات",
      versesCount: "50 Verses",
    ),
    SuraModel(
      id: 78,
      englishName: "An-Naba",
      arabicName: "النبأ",
      versesCount: "40 Verses",
    ),
    SuraModel(
      id: 79,
      englishName: "An-Nazi'at",
      arabicName: "النازعات",
      versesCount: "46 Verses",
    ),
    SuraModel(
      id: 80,
      englishName: "Abasa",
      arabicName: "عبس",
      versesCount: "42 Verses",
    ),
    SuraModel(
      id: 81,
      englishName: "At-Takwir",
      arabicName: "التكوير",
      versesCount: "29 Verses",
    ),
    SuraModel(
      id: 82,
      englishName: "Al-Infitar",
      arabicName: "الانفطار",
      versesCount: "19 Verses",
    ),
    SuraModel(
      id: 83,
      englishName: "Al-Mutaffifin",
      arabicName: "المطففين",
      versesCount: "36 Verses",
    ),
    SuraModel(
      id: 84,
      englishName: "Al-Inshiqaq",
      arabicName: "الانشقاق",
      versesCount: "25 Verses",
    ),
    SuraModel(
      id: 85,
      englishName: "Al-Buruj",
      arabicName: "البروج",
      versesCount: "22 Verses",
    ),
    SuraModel(
      id: 86,
      englishName: "At-Tariq",
      arabicName: "الطارق",
      versesCount: "17 Verses",
    ),
    SuraModel(
      id: 87,
      englishName: "Al-A'la",
      arabicName: "الأعلى",
      versesCount: "19 Verses",
    ),
    SuraModel(
      id: 88,
      englishName: "Al-Ghashiyah",
      arabicName: "الغاشية",
      versesCount: "26 Verses",
    ),
    SuraModel(
      id: 89,
      englishName: "Al-Fajr",
      arabicName: "الفجر",
      versesCount: "30 Verses",
    ),
    SuraModel(
      id: 90,
      englishName: "Al-Balad",
      arabicName: "البلد",
      versesCount: "20 Verses",
    ),
    SuraModel(
      id: 91,
      englishName: "Ash-Shams",
      arabicName: "الشمس",
      versesCount: "15 Verses",
    ),
    SuraModel(
      id: 92,
      englishName: "Al-Layl",
      arabicName: "الليل",
      versesCount: "21 Verses",
    ),
    SuraModel(
      id: 93,
      englishName: "Ad-Duha",
      arabicName: "الضحى",
      versesCount: "11 Verses",
    ),
    SuraModel(
      id: 94,
      englishName: "Ash-Sharh",
      arabicName: "الشرح",
      versesCount: "8 Verses",
    ),
    SuraModel(
      id: 95,
      englishName: "At-Tin",
      arabicName: "التين",
      versesCount: "8 Verses",
    ),
    SuraModel(
      id: 96,
      englishName: "Al-Alaq",
      arabicName: "العلق",
      versesCount: "19 Verses",
    ),
    SuraModel(
      id: 97,
      englishName: "Al-Qadr",
      arabicName: "القدر",
      versesCount: "5 Verses",
    ),
    SuraModel(
      id: 98,
      englishName: "Al-Bayyinah",
      arabicName: "البينة",
      versesCount: "8 Verses",
    ),
    SuraModel(
      id: 99,
      englishName: "Az-Zalzalah",
      arabicName: "الزلزلة",
      versesCount: "8 Verses",
    ),
    SuraModel(
      id: 100,
      englishName: "Al-Adiyat",
      arabicName: "العاديات",
      versesCount: "11 Verses",
    ),
    SuraModel(
      id: 101,
      englishName: "Al-Qari'ah",
      arabicName: "القارعة",
      versesCount: "11 Verses",
    ),
    SuraModel(
      id: 102,
      englishName: "At-Takathur",
      arabicName: "التكاثر",
      versesCount: "8 Verses",
    ),
    SuraModel(
      id: 103,
      englishName: "Al-Asr",
      arabicName: "العصر",
      versesCount: "3 Verses",
    ),
    SuraModel(
      id: 104,
      englishName: "Al-Humazah",
      arabicName: "الهمزة",
      versesCount: "9 Verses",
    ),
    SuraModel(
      id: 105,
      englishName: "Al-Fil",
      arabicName: "الفيل",
      versesCount: "5 Verses",
    ),
    SuraModel(
      id: 106,
      englishName: "Quraysh",
      arabicName: "قريش",
      versesCount: "4 Verses",
    ),
    SuraModel(
      id: 107,
      englishName: "Al-Ma'un",
      arabicName: "الماعون",
      versesCount: "7 Verses",
    ),
    SuraModel(
      id: 108,
      englishName: "Al-Kawthar",
      arabicName: "الكوثر",
      versesCount: "3 Verses",
    ),
    SuraModel(
      id: 109,
      englishName: "Al-Kafirun",
      arabicName: "الكافرون",
      versesCount: "6 Verses",
    ),
    SuraModel(
      id: 110,
      englishName: "An-Nasr",
      arabicName: "النصر",
      versesCount: "3 Verses",
    ),
    SuraModel(
      id: 111,
      englishName: "Al-Masad",
      arabicName: "المسد",
      versesCount: "5 Verses",
    ),
    SuraModel(
      id: 112,
      englishName: "Al-Ikhlas",
      arabicName: "الإخلاص",
      versesCount: "4 Verses",
    ),
    SuraModel(
      id: 113,
      englishName: "Al-Falaq",
      arabicName: "الفلق",
      versesCount: "5 Verses",
    ),
    SuraModel(
      id: 114,
      englishName: "An-Nas",
      arabicName: "الناس",
      versesCount: "6 Verses",
    ),
  ];
}
